# Generated by Django 5.0.7 on 2024-07-31 12:27

import api.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_song_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.ImageField(upload_to=api.helpers.SaveMediaFiles.song_image_save),
        ),
    ]
