# Generated by Django 5.0.7 on 2024-08-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_song_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.URLField(),
        ),
    ]
